name: CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]
        # os: [windows-latest, ubuntu-latest, macos-13, macos-latest, windows-11-arm]
        include:
          - os: windows-latest
            build: BHYG-Windows.exe
          - os: ubuntu-latest
            build: BHYG-Linux
          - os: macos-13
            build: BHYG-macOS-Intel
          - os: macos-latest
            build: BHYG-macOS-Apple_Silicon
          # - os: windows-11-arm
          #   build: BHYG-Windows-arm.exe
    runs-on: ${{ matrix.os }}
    env:
      version: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: biliticket/SB
          token: ${{ secrets.SBCI_TOKEN }}


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Cython
        run: pip install Cython

      - name: Run Cython
        run: python cythonize.py build_ext --inplace

      - name: Remove source code
        if: matrix.os == 'windows-latest'
        run: del api.py main.py bilibili_util.py

      - name: Remove source code
        if: matrix.os != 'windows-latest'
        run: rm api.py main.py bilibili_util.py

      - name: Build Binary
        run: pyinstaller main.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-${{ matrix.build }}
          path: dist/${{ github.ref_name }}-${{ matrix.build }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/${{ github.ref_name }}-${{ matrix.build }}
